<a href="https://colab.research.google.com/github/smritikachowdhury/black-jack-game/blob/main/smritika.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("smritika")

smritika

In [ ]:
print(type(11))

<class 'int'>

In [ ]:
print(type(11.0))
print(type('11'))
print(type("hellow miss 11"))
print(type(True))

<class 'float'>
<class 'str'>
<class 'str'>
<class 'bool'>

In [ ]:
# this is my first comment
# this is line 2

In [ ]:
# here we are printing hello

In [ ]:
'''
here
we
are
printing
hellow
'''

'\nhere\nwe\nare\nprinting\nhellow\n'

In [ ]:
11

11

In [ ]:
print(11)
print(float(11))
print(bool(100))
print(type(str(11)))
print(type(int("11")))
print(type(int("a")))

11
11.0
True
<class 'str'>
<class 'int'>

ValueError: invalid literal for int() with base 10: 'a'

In [ ]:
print(bool(1))
print(bool(0))

True
False

In [ ]:
print(10+5)
print(10-20)
print(5*5)
print(25/25)

15
-10
25
1.0

In [ ]:
print(25/6)
print(25//6)
print(-21/6)
print(-21//6)

4.166666666666667
4
-3.5
-4

In [ ]:
print(10+4*2)
print((10+5)*2)

18
30

In [ ]:
x=10   # x is stroing the vaiue 10
print(x)

10

In [ ]:
x=10
x=20        #latestvalue replaces the old one
print(x)

20

In [ ]:
x=10+5       # variables can store results also
print(x)

15

In [ ]:
x=10
y=x/3

In [ ]:
x=10
y=x/3
result =(x+y)
print(result)

13.333333333333334

In [ ]:
py=7
m=9
ee=10
tm=py+m+ee
print(tm)
persentage=(tm*3)/100
print(persentage)

26
0.78

In [ ]:
name=input("enter name :")
print(name)

enter name :smriyika
smriyika

In [ ]:
age=int(input("enter your age :"))
print(type(age))
print(age+4)

enter your age :56
<class 'int'>
60

In [ ]:
name ="michael jackson"
print(type(name))
print(len(name))

<class 'str'>
15

In [ ]:
name[0:4]

'mich'

In [ ]:
name[:]

'michael jackson'

In [ ]:
name[::-1]

'noskcaj leahcim'

In [ ]:
name[1:10:2]

'ihe a'

In [ ]:
name= "virat kohli"
name[0:10]

'virat kohl'

In [ ]:
name[0:10:2]

'vrtkh'

In [ ]:
name[::-1]

'ilhok tariv'

In [ ]:
compiment=name+" is the best"
print('compliment')

compliment

In [ ]:
name = "smrRiTika"
print(name.capitalize())

Smrritika

In [ ]:
print("C:\\Users\\smritika")

C:\Users\smritika

In [ ]:
#if statements
marks = int(input("enter your marks:"))
if marks >=40:
  print("pass")
else:
  print("fail")

enter your marks:56
pass

In [ ]:
marks=int(input("enter your marks:"))
if marks>=80:
  print("A");
elif marks>=60:
   print("B");
else:
    print("c");

enter your marks:79
B

In [ ]:
total=0
x=int(input("enter the number :"))
for i in range(1,x):
  total=total+i

print("total:",total)

enter the number :1
total: 0

In [ ]:
i=1

while i<=11:
  print(i)
  i=i+3

1
4
7
10

In [ ]:
for i in range(1,10):
  if i== 3:
    continue
  if i == 5:
    break
  print(i)

1
2
4

In [ ]:


def greet(name):
  print("hellow",name)

greet("smritika")

hellow smritika

In [ ]:
def add(a,b):
  '''
  this function add 2 number
  '''
  return a+b

result=add(2,3)
help(add)
print(result)

Help on function add in module __main__:

add(a, b)
    this function add 2 number

5

In [ ]:
number =[10,20,30,40]
list =[1,2,3,4]
print(number)

[10, 20, 30, 40]

In [ ]:
list =[10,20,30,"apple",true]

In [ ]:
list[0] =15
print(list)

[15, 2, 3, 4]

In [ ]:
fruits =["apple","banana","mango"]
mixed =[10,"hello",3.5,True]
print(number)
print(fruits)
print(mixed)
type(fruits)

[10, 20, 30, 40]
['apple', 'banana', 'mango']
[10, 'hello', 3.5, True]

list

In [ ]:
fruits =["apple","banana","mango"]
fruits[1]="orange"
print(fruits)

['apple', 'orange', 'mango']

In [ ]:
list =[10,20,30,40,50,60,70,]
print(list[1:4])

[20, 30, 40]

In [ ]:
print(list[-4:-1])

[40, 50, 60]

In [ ]:
print(list[::-1])

[70, 60, 50, 40, 30, 20, 10]

In [ ]:
list =[4,10,15,20,25,30]
print(list[3:])

[20, 25, 30]

In [ ]:
list = [1,2,3,4,5,6,7,8]
even_index = list[::2]
odd_index = list[1::2]
print("even index list:",even_index)
print("odd index list", odd_index)

even index list: [1, 3, 5, 7]
odd index list [2, 4, 6, 8]

In [ ]:
list =[1,2,3]
list.append(4)
print(list)

[1, 2, 3, 4]

In [ ]:
lst =[1,2,3]
lst.insert(1,100)
print(lst)

[1, 100, 2, 3]

In [ ]:
lst =[1,2,3]
lst.clear()
print(lst)

[]

In [ ]:
list =[10,20,30]
print(list.index(20))

1

In [ ]:
lst = [1,2,2,3]
print(lst.count(2))

2

In [ ]:
list = [1,2,3]
list.reverse()
print(list)

[3, 2, 1]

In [ ]:
t = (5)
t =(5)
t1 =(1,2,3)
t2 =("a","b","c","d")
print(t1)
print(t2)

(1, 2, 3)
('a', 'b', 'c', 'd')

In [ ]:
t = (1,2,3,4,5,2,2,2)
x =t.index(2)
print(2)

2

In [ ]:
xy ={
    "name":"smritika"
}
print(type(xy))
xy["word"]="mining"
print(xy)

<class 'dict'>
{'name': 'smritika', 'word': 'mining'}

In [ ]:
dic = {
    "name" :"aditi",
    "subject":["python","c","java"],
    "age" : 21,
    "is_adult" : True,
    "topics" : ("dict","set")
}
print(dic,"\n")
print(dic["name"])
print(dic["subject"])

{'name': 'aditi', 'subject': ['python', 'c', 'java'], 'age': 21, 'is_adult': True, 'topics': ('dict', 'set')}

aditi
['python', 'c', 'java']

In [ ]:
s1 ={1,2,3,4,5,67,89,2}

print(s1)
print(type(s1))

{1, 2, 3, 4, 5, 67, 89}
<class 'set'>

In [ ]:
s =pd.Series([1,2,3,4,5 , 23,45,67])
print(s)
print(type(s))

NameError: name 'pandas' is not defined

In [ ]:
import pandas as pd

In [ ]:
s =pd.Series([1,2,3,4,5 , 23,45,67])
print(s)
print(type(s))

0     1
1     2
2     3
3     4
4     5
5    23
6    45
7    67
dtype: int64
<class 'pandas.core.series.Series'>

In [ ]:
s.head()

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
data ={
    "name": ["a", "b","c"],
    "marks":[90,80,85]
}
df = pd.Data

In [ ]:
df = pd.read_csv("student-data.csv")
print(df)

    school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
0       GP   F   18       U     GT3       A     4     4   at_home   teacher
1       GP   F   17       U     GT3       T     1     1   at_home     other
2       GP   F   15       U     LE3       T     1     1   at_home     other
3       GP   F   15       U     GT3       T     4     2    health  services
4       GP   F   16       U     GT3       T     3     3     other     other
..     ...  ..  ...     ...     ...     ...   ...   ...       ...       ...
390     MS   M   20       U     LE3       A     2     2  services  services
391     MS   M   17       U     LE3       T     3     1  services  services
392     MS   M   21       R     GT3       T     1     1     other     other
393     MS   M   18       R     LE3       T     3     2  services     other
394     MS   M   19       U     LE3       T     1     1     other   at_home

     ... internet romantic  famrel  freetime  goout Dalc Walc health absences  \
0    ...       no       no       4         3      4    1    1      3        6
1    ...      yes       no       5         3      3    1    1      3        4
2    ...      yes       no       4         3      2    2    3      3       10
3    ...      yes      yes       3         2      2    1    1      5        2
4    ...       no       no       4         3      2    1    2      5        4
..   ...      ...      ...     ...       ...    ...  ...  ...    ...      ...
390  ...       no       no       5         5      4    4    5      4       11
391  ...      yes       no       2         4      5    3    4      2        3
392  ...       no       no       5         5      3    3    3      3        3
393  ...      yes       no       4         4      1    3    4      5        0
394  ...      yes       no       3         2      3    3    3      5        5

    passed
0       no
1       no
2      yes
3      yes
4      yes
..     ...
390     no
391    yes
392     no
393    yes
394     no

[395 rows x 31 columns]

In [ ]:
df.head(2)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,passed
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,no,no,4,3,4,1,1,3,6,no
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,yes,no,5,3,3,1,1,3,4,no

In [ ]:
df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,passed
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,no,no,4,3,4,1,1,3,6,no
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,yes,no,5,3,3,1,1,3,4,no
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,yes,no,4,3,2,2,3,3,10,yes
3,GP,F,15,U,GT3,T,4,2,health,services,...,yes,yes,3,2,2,1,1,5,2,yes
4,GP,F,16,U,GT3,T,3,3,other,other,...,no,no,4,3,2,1,2,5,4,yes

In [ ]:
df.tail()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,passed
390,MS,M,20,U,LE3,A,2,2,services,services,...,no,no,5,5,4,4,5,4,11,no
391,MS,M,17,U,LE3,T,3,1,services,services,...,yes,no,2,4,5,3,4,2,3,yes
392,MS,M,21,R,GT3,T,1,1,other,other,...,no,no,5,5,3,3,3,3,3,no
393,MS,M,18,R,LE3,T,3,2,services,other,...,yes,no,4,4,1,3,4,5,0,yes
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,yes,no,3,2,3,3,3,5,5,no

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 31 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   school      395 non-null    object
 1   sex         395 non-null    object
 2   age         395 non-null    int64
 3   address     395 non-null    object
 4   famsize     395 non-null    object
 5   Pstatus     395 non-null    object
 6   Medu        395 non-null    int64
 7   Fedu        395 non-null    int64
 8   Mjob        395 non-null    object
 9   Fjob        395 non-null    object
 10  reason      395 non-null    object
 11  guardian    395 non-null    object
 12  traveltime  395 non-null    int64
 13  studytime   395 non-null    int64
 14  failures    395 non-null    int64
 15  schoolsup   395 non-null    object
 16  famsup      395 non-null    object
 17  paid        395 non-null    object
 18  activities  395 non-null    object
 19  nursery     395 non-null    object
 20  higher      395 non-null    object
 21  internet    395 non-null    object
 22  romantic    395 non-null    object
 23  famrel      395 non-null    int64
 24  freetime    395 non-null    int64
 25  goout       395 non-null    int64
 26  Dalc        395 non-null    int64
 27  Walc        395 non-null    int64
 28  health      395 non-null    int64
 29  absences    395 non-null    int64
 30  passed      395 non-null    object
dtypes: int64(13), object(18)
memory usage: 95.8+ KB

In [ ]:
df.shape

(395, 31)

In [ ]:
df.describe()

,age,Medu,Fedu,traveltime,studytime,failures,famrel,freetime,goout,Dalc,Walc,health,absences
count,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000
mean,16.696203,2.749367,2.521519,1.448101,2.035443,0.334177,3.944304,3.235443,3.108861,1.481013,2.291139,3.554430,5.708861
std,1.276043,1.094735,1.088201,0.697505,0.839240,0.743651,0.896659,0.998862,1.113278,0.890741,1.287897,1.390303,8.003096
min,15.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000
25%,16.000000,2.000000,2.000000,1.000000,1.000000,0.000000,4.000000,3.000000,2.000000,1.000000,1.000000,3.000000,0.000000
50%,17.000000,3.000000,2.000000,1.000000,2.000000,0.000000,4.000000,3.000000,3.000000,1.000000,2.000000,4.000000,4.000000
75%,18.000000,4.000000,3.000000,2.000000,2.000000,0.000000,5.000000,4.000000,4.000000,2.000000,3.000000,5.000000,8.000000
max,22.000000,4.000000,4.000000,4.000000,4.000000,3.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,75.000000

In [ ]:
df.columns

Index(['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime',
       'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery',
       'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc',
       'Walc', 'health', 'absences', 'passed'],
      dtype='object')

In [ ]:
df["Fjob"]

0       teacher
1         other
2         other
3      services
4         other
         ...
390    services
391    services
392       other
393       other
394     at_home
Name: Fjob, Length: 395, dtype: object

In [ ]:
df[["Fjob","romantic"]]

         Fjob romantic
0     teacher       no
1       other       no
2       other       no
3    services      yes
4       other       no
..        ...      ...
390  services       no
391  services       no
392     other       no
393     other       no
394   at_home       no

[395 rows x 2 columns]

In [ ]:
df.iloc[0:3]

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,passed
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,no,no,4,3,4,1,1,3,6,no
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,yes,no,5,3,3,1,1,3,4,no
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,yes,no,4,3,2,2,3,3,10,yes

In [ ]:
df.isnull()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,passed
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
391,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
392,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
393,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
394,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [ ]:
df.isnull().sum()

school        0
sex           0
age           0
address       0
famsize       0
Pstatus       0
Medu          0
Fedu          0
Mjob          0
Fjob          0
reason        0
guardian      0
traveltime    0
studytime     0
failures      0
schoolsup     0
famsup        0
paid          0
activities    0
nursery       0
higher        0
internet      0
romantic      0
famrel        0
freetime      0
goout         0
Dalc          0
Walc          0
health        0
absences      0
passed        0
dtype: int64

In [ ]:
df.dropna()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,passed
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,no,no,4,3,4,1,1,3,6,no
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,yes,no,5,3,3,1,1,3,4,no
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,yes,no,4,3,2,2,3,3,10,yes
3,GP,F,15,U,GT3,T,4,2,health,services,...,yes,yes,3,2,2,1,1,5,2,yes
4,GP,F,16,U,GT3,T,3,3,other,other,...,no,no,4,3,2,1,2,5,4,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,services,services,...,no,no,5,5,4,4,5,4,11,no
391,MS,M,17,U,LE3,T,3,1,services,services,...,yes,no,2,4,5,3,4,2,3,yes
392,MS,M,21,R,GT3,T,1,1,other,other,...,no,no,5,5,3,3,3,3,3,no
393,MS,M,18,R,LE3,T,3,2,services,other,...,yes,no,4,4,1,3,4,5,0,yes
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,yes,no,3,2,3,3,3,5,5,no

In [ ]:
import numpy as np

In [ ]:
a=[1,"smritika",2.676,"riya"]
print(a)

[1, 'smritika', 2.676, 'riya']

In [ ]:
c = np.array([[[[2]]]])
c.ndim

4

In [13]:

import random

In [14]:
card_categories =['hearts','diamonds','clubs','spades']
cards_list =['ace','2','3','4','5','6','7','8','9','10','jack','queen','king']
deck =[(card,category) for category in card_categories for card in cards_list]

In [15]:
def card_value(card):
  if card[0] in ['jack','queen','king']:
    return 10
  elif card[0] =='ace':
    return 11
  else:
    return int(card[0])

In [16]:
random.shuffle(deck)
player_card=[deck.pop(),deck.pop()]
dealer_card=[deck.pop(),deck.pop()]

In [28]:
while True:
  player_score = sum(card_value(card) for card in player_card)
  dealer_score = sum(card_value(card) for card in dealer_card)
  print("crard player Has:",player_card)
  print("score of The players:",player_score)
  print("\n")
  choice = input('what do you want?["play" to request another card,"stop" to stop]:').lower()
  if choice == "play":
    new_card = deck.pop()
    player_card.append(new_card)
  elif choice =="stop":
      break
  else:
    print("invalid choice.please try again.")
    continue

  if player_score >21:
   print("cards dealer has:",dealer_card)
   print("score of the Dealer:",dealer_card)
   print("cards dealer has:",dealer_card)
   print("score of the dealer:",dealer_card)
   print("Dealer wins (player loss Because Player score is exceeding 21)")
   break

crard player Has: [('4', 'spades'), ('8', 'diamonds')]
score of The players: 12


what do you want?["play" to request another card,"stop" to stop]:play
invalid choice.please try again.
crard player Has: [('4', 'spades'), ('8', 'diamonds')]
score of The players: 12


what do you want?["play" to request another card,"stop" to stop]:play
crard player Has: [('4', 'spades'), ('8', 'diamonds'), ('8', 'clubs')]
score of The players: 20


what do you want?["play" to request another card,"stop" to stop]:stop

In [29]:
#dealer has to draw cards now
while dealer_score < 17:
    new_card = deck.pop()
    dealer_card.append(new_card)
    dealer_score += card_value(new_card)

print("Cards Dealer Has:", dealer_card)
print("Score Of The Dealer:", dealer_score)
print("\n")

Cards Dealer Has: [('king', 'hearts'), ('ace', 'diamonds')]
Score Of The Dealer: 21

In [31]:
#decision wala code hai ye omggg who will win guess karna
if dealer_score > 21:
    print("Cards Dealer Has:", dealer_card)
    print("Score Of The Dealer:", dealer_score)
    print("Cards Player Has:", player_card)
    print("Score Of The Player:", player_score)
    print("Player wins (Dealer Loss Because Dealer Score is exceeding 21)")
elif player_score > dealer_score:
    print("Cards Dealer Has:", dealer_card)
    print("Score Of The Dealer:", dealer_score)
    print("Cards Player Has:", player_card)
    print("Score Of The Player:", player_score)
    print("Player wins (Player Has High Score than Dealer)")
elif dealer_score > player_score:
    print("Cards Dealer Has:", dealer_card)
    print("Score Of The Dealer:", dealer_score)
    print("Cards Player Has:", player_card)
    print("Score Of The Player:", player_score)
    print("Dealer wins (Dealer Has High Score than Player)")
else:
    print("Cards Dealer Has:", dealer_card)
    print("Score Of The Dealer:", dealer_score)
    print("Cards Player Has:", player_card)
    print("Score Of The Player:", player_score)
    print("It's a tie.")

Cards Dealer Has: [('king', 'hearts'), ('ace', 'diamonds')]
Score Of The Dealer: 21
Cards Player Has: [('4', 'spades'), ('8', 'diamonds'), ('8', 'clubs')]
Score Of The Player: 20
Dealer wins (Dealer Has High Score than Player)